nodeLinker: node-modules

npmPublishProvenance: false

npmRegistryServer: 'https://registry.npmjs.org'
npmPublishRegistry: "https://registry.npmjs.org"

npmScopes:
  quonfig:
    npmRegistryServer: "https://registry.npmjs.org"
    npmPublishRegistry: "https://registry.npmjs.org"
