import {stripIndent} from 'common-tags'
import camelCase from 'lodash.camelcase'

import {ZodToTypescriptMapper, type ZodToTypescriptMapperTarget} from '../language-mappers/zod-to-typescript-mapper.js'
import {ZodToTypescriptReturnValueMapper} from '../language-mappers/zod-to-typescript-return-value-mapper.js'
import {BaseTypescriptGenerator} from './base-typescript-generator.js'

export class NodeTypeScriptGenerator extends BaseTypescriptGenerator {
  declarationGenerate(): string {
    return (
      stripIndent`
    /* eslint-disable */
    // AUTOGENERATED by quonfig-cli's 'gen' command
    // prettier-ignore
    import "@quonfig/node";

    // prettier-ignore
    declare module "@quonfig/node" {
      export interface NodeServerConfigurationRaw {
        ${this.generateSchemaTypes('raw').join('\n        ') || '// No types generated'}
      }

      export interface NodeServerConfigurationAccessor {
        ${this.generateSchemaTypes().join('\n        ') || '// No types generated'}
      }
    }
    ` + '\n' // For adding newline to avoid prettier issues
    )
  }

  generate(): string {
    return (
      stripIndent`
    /* eslint-disable */
    // AUTOGENERATED by quonfig-cli's 'gen' command
    // prettier-ignore
    import { Quonfig, Contexts, TypedNodeServerConfigurationRaw, TypedNodeServerConfigurationAccessor } from '@quonfig/node'
    // prettier-ignore
    ${this.additionalDependencies().join('\n// prettier-ignore\n') || '// No additional dependencies required'}

    // prettier-ignore
    type ContextObj = Record<string, Record<string, unknown>>

    // prettier-ignore
    export class QuonfigTypesafeNode {
      constructor(public quonfig: Quonfig) { }

      get<K extends keyof TypedNodeServerConfigurationRaw>(key: K, contexts?: Contexts | ContextObj): TypedNodeServerConfigurationRaw[K] {
        return this.quonfig.get(key, contexts) as TypedNodeServerConfigurationRaw[K]
      }

      ${this.generateAccessorMethods().join('\n\n      ') || '// No methods generated'}
    }
    ` + '\n' // For adding newline to avoid prettier issues
    )
  }

  private additionalDependencies(): string[] {
    const dependencies: string[] = []
    const hasFunctions = this.configurations().some((c) => c.hasFunction)

    if (hasFunctions) {
      dependencies.push(this.MUSTACHE_IMPORT)
    }

    return dependencies
  }

  private generateAccessorMethods(): string[] {
    const uniqueMethods: Record<string, string> = {}
    const schemaTypes = this.configurations().map((config) => {
      let methodName = camelCase(config.key)

      // If the method name starts with a digit, prefix it with an underscore to ensure method name is valid
      if (/^\d/.test(methodName)) {
        methodName = `_${methodName}`
      }

      if (uniqueMethods[methodName]) {
        throw new Error(
          `Method '${methodName}' is already registered. Quonfig key ${config.key} conflicts with '${uniqueMethods[methodName]}'!`,
        )
      }

      uniqueMethods[methodName] = config.key

      if (config.hasFunction) {
        const returnValue = new ZodToTypescriptReturnValueMapper().resolveType(config.schema)

        return stripIndent`
          ${methodName}(contexts?: Contexts | ContextObj): TypedNodeServerConfigurationAccessor['${config.key}'] {
                  const raw = this.get('${config.key}', contexts)
                  return ${returnValue}
                }
          `
      }

      return stripIndent`
        ${methodName}(contexts?: Contexts | ContextObj): TypedNodeServerConfigurationAccessor['${config.key}'] {
                return this.get('${config.key}', contexts)
              }
          `
    })

    return schemaTypes
  }

  private generateSchemaTypes(target: ZodToTypescriptMapperTarget = 'accessor'): string[] {
    const schemaTypes = this.configurations().flatMap((config) => {
      const mapper = new ZodToTypescriptMapper({fieldName: config.key, target})

      return mapper.renderField(config.schema)
    })

    return schemaTypes
  }
}
