import {stripIndent} from 'common-tags'

import {ZodToTypescriptMapper, type ZodToTypescriptMapperTarget} from '../language-mappers/zod-to-typescript-mapper.js'
import {ZodToTypescriptReturnValueMapper} from '../language-mappers/zod-to-typescript-return-value-mapper.js'
import {BaseTypescriptGenerator} from './base-typescript-generator.js'

export class NodeTypeScriptGenerator extends BaseTypescriptGenerator {
  declarationGenerate(): string {
    return (
      stripIndent`
    /* eslint-disable */
    // AUTOGENERATED by quonfig-cli's 'generate' command
    // prettier-ignore
    import "@quonfig/node";

    // prettier-ignore
    declare module "@quonfig/node" {
      export interface NodeServerConfigurationRaw {
        ${this.generateSchemaTypes('raw').join('\n        ') || '// No types generated'}
      }

      export interface NodeServerConfigurationAccessor {
        ${this.generateSchemaTypes().join('\n        ') || '// No types generated'}
      }
    }
    ` + '\n' // For adding newline to avoid prettier issues
    )
  }

  generate(): string {
    return (
      stripIndent`
    /* eslint-disable */
    // AUTOGENERATED by quonfig-cli's 'generate' command
    // prettier-ignore
    import { Quonfig, Contexts, TypedNodeServerConfigurationRaw, TypedNodeServerConfigurationAccessor } from '@quonfig/node'
    // prettier-ignore
    ${this.additionalDependencies().join('\n// prettier-ignore\n') || '// No additional dependencies required'}

    // prettier-ignore
    type ContextObj = Record<string, Record<string, unknown>>

    // prettier-ignore
    export class QuonfigTypesafeNode {
      constructor(public quonfig: Quonfig) { }

      get<K extends keyof TypedNodeServerConfigurationRaw>(key: K, contexts?: Contexts | ContextObj): TypedNodeServerConfigurationRaw[K] {
        return this.quonfig.get(key, contexts) as TypedNodeServerConfigurationRaw[K]
      }

      ${this.generateAccessorMethods().join('\n\n      ') || '// No methods generated'}
    }
    ` + '\n' // For adding newline to avoid prettier issues
    )
  }

  private additionalDependencies(): string[] {
    const dependencies: string[] = []
    const hasFunctions = this.configurations().some((c) => c.hasFunction)

    if (hasFunctions) {
      dependencies.push(this.MUSTACHE_IMPORT)
    }

    return dependencies
  }

  private generateAccessorMethods(): string[] {
    const configs = this.configurations()
    // qfg-hbuy.8: colliding camelCased identifiers get deterministic numeric
    // suffixes (with a warning) instead of throwing — see the base class.
    const {collisions, methodNameByKey} = this.assignAccessorMethodNames(configs.map((c) => c.key))
    this.warnOnAccessorNameCollisions(collisions)

    const schemaTypes = configs.map((config) => {
      const methodName = methodNameByKey.get(config.key)!

      if (config.hasFunction) {
        const returnValue = new ZodToTypescriptReturnValueMapper().resolveType(config.schema)

        return stripIndent`
          ${methodName}(contexts?: Contexts | ContextObj): TypedNodeServerConfigurationAccessor['${config.key}'] {
                  const raw = this.get('${config.key}', contexts)
                  return ${returnValue}
                }
          `
      }

      return stripIndent`
        ${methodName}(contexts?: Contexts | ContextObj): TypedNodeServerConfigurationAccessor['${config.key}'] {
                return this.get('${config.key}', contexts)
              }
          `
    })

    return schemaTypes
  }

  private generateSchemaTypes(target: ZodToTypescriptMapperTarget = 'accessor'): string[] {
    const schemaTypes = this.configurations().flatMap((config) => {
      const mapper = new ZodToTypescriptMapper({fieldName: config.key, target})

      return mapper.renderField(config.schema)
    })

    return schemaTypes
  }
}
