import {stripIndent} from 'common-tags'
import {z} from 'zod'

import {ZodToTypescriptMapper, type ZodToTypescriptMapperTarget} from '../language-mappers/zod-to-typescript-mapper.js'
import {ZodToTypescriptReturnValueMapper} from '../language-mappers/zod-to-typescript-return-value-mapper.js'
import {BaseTypescriptGenerator} from './base-typescript-generator.js'

export class ReactTypeScriptGenerator extends BaseTypescriptGenerator {
  declarationGenerate(): string {
    return (
      stripIndent`
    /* eslint-disable */
    // AUTOGENERATED by quonfig-cli's 'generate' command
    // prettier-ignore
    import "@quonfig/javascript";
    // prettier-ignore
    import "@quonfig/react";

    // prettier-ignore
    declare module "@quonfig/javascript" {
      export interface FrontEndConfigurationRaw {
        ${this.generateSchemaTypes('raw').join('\n        ') || '// No types generated'}
      }

      // Force TypedFrontEndConfigurationRaw to always use our merged interface
      export type TypedFrontEndConfigurationRaw = FrontEndConfigurationRaw;
    }

    // prettier-ignore
    declare module "@quonfig/react" {
      export interface FrontEndConfigurationAccessor {
        ${this.generateSchemaTypes().join('\n        ') || '// No types generated'}
      }

      // Force TypedFrontEndConfigurationRaw to always use our merged interface
      export type TypedFrontEndConfigurationAccessor = FrontEndConfigurationAccessor;
    }
    ` + '\n' // For adding newline to avoid prettier issues
    )
  }

  protected durationTypeMap(): z.ZodTypeAny {
    return z.object({ms: z.number(), seconds: z.number()})
  }

  generate(): string {
    return (
      stripIndent`
    /* eslint-disable */
    // AUTOGENERATED by quonfig-cli's 'generate' command
    // prettier-ignore
    import { Quonfig, TypedFrontEndConfigurationRaw } from "@quonfig/javascript"
    // prettier-ignore
    import { createQuonfigHook, TypedFrontEndConfigurationAccessor } from "@quonfig/react"
    // prettier-ignore
    ${this.additionalDependencies().join('\n// prettier-ignore\n') || '// No additional dependencies required'}

    // prettier-ignore
    export class QuonfigTypesafeReact {
      constructor(public quonfig: Quonfig) { }

      get<K extends keyof TypedFrontEndConfigurationRaw>(key: K): TypedFrontEndConfigurationRaw[K] {
        return this.quonfig.get(key) as TypedFrontEndConfigurationRaw[K]
      }

      ${this.generateAccessorMethods().join('\n\n      ') || '// No methods generated'}
    }

    // prettier-ignore
    export const useQuonfig = createQuonfigHook(QuonfigTypesafeReact)
    ` + '\n' // For adding newline to avoid prettier issues
    )
  }

  private additionalDependencies(): string[] {
    const dependencies: string[] = []
    const hasFunctions = this.filteredConfigurations().some((c) => c.hasFunction)

    if (hasFunctions) {
      dependencies.push(this.MUSTACHE_IMPORT)
    }

    return dependencies
  }

  private filteredConfigurations() {
    return this.configurations().filter(
      (config) => config.configType === 'FEATURE_FLAG' || config.sendToClientSdk === true,
    )
  }

  private generateAccessorMethods(): string[] {
    const configs = this.filteredConfigurations()
    // qfg-hbuy.8: colliding camelCased identifiers get deterministic numeric
    // suffixes (with a warning) instead of throwing — see the base class. Runs
    // on the client-side-filtered set, so a collision among server-only keys
    // does not affect (or warn in) the react output.
    const {collisions, methodNameByKey} = this.assignAccessorMethodNames(configs.map((c) => c.key))
    this.warnOnAccessorNameCollisions(collisions)

    const schemaTypes = configs.map((config) => {
      const methodName = methodNameByKey.get(config.key)!

      if (config.hasFunction) {
        const returnValue = new ZodToTypescriptReturnValueMapper().resolveType(config.schema)

        return stripIndent`
          ${methodName}(): TypedFrontEndConfigurationAccessor['${config.key}'] {
                  const raw = this.get('${config.key}')
                  return ${returnValue}
                }
          `
      }

      return stripIndent`
        get ${methodName}(): TypedFrontEndConfigurationAccessor['${config.key}'] {
                return this.get('${config.key}')
              }
        `
    })

    return schemaTypes
  }

  private generateSchemaTypes(target: ZodToTypescriptMapperTarget = 'accessor'): string[] {
    const schemaTypes = this.filteredConfigurations().map((config) => {
      const mapper = new ZodToTypescriptMapper({fieldName: config.key, target})

      return mapper.renderField(config.schema)
    })

    return schemaTypes
  }
}
