import {expect} from 'chai'
import {stripIndent} from 'common-tags'

import {NodeTypeScriptGenerator} from '../../../src/codegen/code-generators/node-typescript-generator.js'
import {type ConfigFile} from '../../../src/codegen/types.js'

const mockLog: (category: string | unknown, message?: unknown) => void = () => {}
const defaultMockConfigFile: ConfigFile = {
  configs: [],
}

describe('NodeTypeScriptGenerator', () => {
  describe('declarationGenerate', () => {
    it('should generate basic code structure when no configs exist', () => {
      const generator = new NodeTypeScriptGenerator({
        configFile: defaultMockConfigFile,
        log: mockLog,
      })

      const result = generator.declarationGenerate()

      expect(result).to.equal(
        stripIndent`
      /* eslint-disable */
      // AUTOGENERATED by quonfig-cli's 'generate' command
      // prettier-ignore
      import "@quonfig/node";

      // prettier-ignore
      declare module "@quonfig/node" {
        export interface NodeServerConfigurationRaw {
          // No types generated
        }

        export interface NodeServerConfigurationAccessor {
          // No types generated
        }
      }
      ` + '\n',
      )
    })

    it('should generate type definitions for configs and feature flags, not schema, or empty configurations', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'config1',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            valueType: 'STRING',
          },
          {
            configType: 'CONFIG',
            key: 'emptyConfig',
            rows: [],
            valueType: 'STRING',
          },
          {
            configType: 'FEATURE_FLAG',
            key: 'flag1',
            rows: [{values: [{value: {bool: true}}]}],
            valueType: 'BOOL',
          },
          {
            configType: 'FEATURE_FLAG',
            key: 'emptyFlag',
            rows: [],
            valueType: 'BOOL',
          },
          {
            configType: 'SCHEMA',
            key: 'schema1',
            rows: [{values: [{value: {bool: true}}]}],
            valueType: 'BOOL',
          },
        ],
      }

      const generator = new NodeTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.declarationGenerate()

      expect(result).to.equal(
        stripIndent`
      /* eslint-disable */
      // AUTOGENERATED by quonfig-cli's 'generate' command
      // prettier-ignore
      import "@quonfig/node";

      // prettier-ignore
      declare module "@quonfig/node" {
        export interface NodeServerConfigurationRaw {
          "config1": string
          "flag1": boolean
        }

        export interface NodeServerConfigurationAccessor {
          "config1": string
          "flag1": boolean
        }
      }
      ` + '\n',
      )
    })

    it('should generate function accessor methods for function configs', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'config1',
            rows: [{values: [{value: {string: 'Hello, {{name}}!'}}]}],
            valueType: 'STRING',
          },
        ],
      }

      const generator = new NodeTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.declarationGenerate()

      expect(result).to.equal(
        stripIndent`
      /* eslint-disable */
      // AUTOGENERATED by quonfig-cli's 'generate' command
      // prettier-ignore
      import "@quonfig/node";

      // prettier-ignore
      declare module "@quonfig/node" {
        export interface NodeServerConfigurationRaw {
          "config1": string | undefined
        }

        export interface NodeServerConfigurationAccessor {
          "config1": (...params: [{ "name": string }]) => string
        }
      }
      ` + '\n',
      )
    })

    it('should generate durations correctly', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'config1',
            rows: [{values: [{value: {int: 1}}]}],
            valueType: 'DURATION',
          },
        ],
      }

      const generator = new NodeTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.declarationGenerate()

      expect(result).to.equal(
        stripIndent`
      /* eslint-disable */
      // AUTOGENERATED by quonfig-cli's 'generate' command
      // prettier-ignore
      import "@quonfig/node";

      // prettier-ignore
      declare module "@quonfig/node" {
        export interface NodeServerConfigurationRaw {
          "config1": number
        }

        export interface NodeServerConfigurationAccessor {
          "config1": number
        }
      }
      ` + '\n',
      )
    })

    it('should prefix method names with underscore when they start with a digit', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: '1config',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            valueType: 'STRING',
          },
          {
            configType: 'FEATURE_FLAG',
            key: '1flag',
            rows: [{values: [{value: {bool: true}}]}],
            valueType: 'BOOL',
          },
        ],
      }

      const generator = new NodeTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.declarationGenerate()

      expect(result).to.equal(
        stripIndent`
      /* eslint-disable */
      // AUTOGENERATED by quonfig-cli's 'generate' command
      // prettier-ignore
      import "@quonfig/node";

      // prettier-ignore
      declare module "@quonfig/node" {
        export interface NodeServerConfigurationRaw {
          "1config": string
          "1flag": boolean
        }

        export interface NodeServerConfigurationAccessor {
          "1config": string
          "1flag": boolean
        }
      }
      ` + '\n',
      )
    })

    it('should properly camelCase various key formats', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'snake_case_key',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            valueType: 'STRING',
          },
          {
            configType: 'FEATURE_FLAG',
            key: 'kebab-case-key',
            rows: [{values: [{value: {bool: true}}]}],
            valueType: 'BOOL',
          },
          {
            configType: 'CONFIG',
            key: 'dot.notation.key',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            valueType: 'STRING',
          },
          {
            configType: 'FEATURE_FLAG',
            key: 'UPPER_CASE_KEY',
            rows: [{values: [{value: {bool: true}}]}],
            valueType: 'BOOL',
          },
          {
            configType: 'CONFIG',
            key: 'key_with_$_special',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            valueType: 'STRING',
          },
          {
            configType: 'FEATURE_FLAG',
            key: 'key/with/slashes',
            rows: [{values: [{value: {bool: true}}]}],
            valueType: 'BOOL',
          },
        ],
      }

      const generator = new NodeTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.declarationGenerate()

      expect(result).to.equal(
        stripIndent`
      /* eslint-disable */
      // AUTOGENERATED by quonfig-cli's 'generate' command
      // prettier-ignore
      import "@quonfig/node";

      // prettier-ignore
      declare module "@quonfig/node" {
        export interface NodeServerConfigurationRaw {
          "dot.notation.key": string
          "kebab-case-key": boolean
          "key_with_$_special": string
          "key/with/slashes": boolean
          "snake_case_key": string
          "UPPER_CASE_KEY": boolean
        }

        export interface NodeServerConfigurationAccessor {
          "dot.notation.key": string
          "kebab-case-key": boolean
          "key_with_$_special": string
          "key/with/slashes": boolean
          "snake_case_key": string
          "UPPER_CASE_KEY": boolean
        }
      }` + '\n',
      )
    })
  })

  describe('generate', () => {
    it('should generate basic code structure when no configs exist', () => {
      const generator = new NodeTypeScriptGenerator({
        configFile: defaultMockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      expect(result).to.equal(
        stripIndent`
      /* eslint-disable */
      // AUTOGENERATED by quonfig-cli's 'generate' command
      // prettier-ignore
      import { Quonfig, Contexts, TypedNodeServerConfigurationRaw, TypedNodeServerConfigurationAccessor } from '@quonfig/node'
      // prettier-ignore
      // No additional dependencies required

      // prettier-ignore
      type ContextObj = Record<string, Record<string, unknown>>

      // prettier-ignore
      export class QuonfigTypesafeNode {
        constructor(public quonfig: Quonfig) { }

        get<K extends keyof TypedNodeServerConfigurationRaw>(key: K, contexts?: Contexts | ContextObj): TypedNodeServerConfigurationRaw[K] {
          return this.quonfig.get(key, contexts) as TypedNodeServerConfigurationRaw[K]
        }

        // No methods generated
      }` + '\n',
      )
    })

    it('should include Mustache import when function configs exist', () => {
      // Use mustache syntax for the template to ensure a function is generated
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'some-key',
            rows: [{values: [{value: {string: 'Hello, {{name}}!'}}]}],
            valueType: 'STRING',
          },
        ],
      }
      const generator = new NodeTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      // Verify Mustache import is included
      expect(result).to.include("import Mustache from 'mustache'")
    })

    it('should generate type definitions for configs and feature flags, not schema, or empty configurations', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'config1',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            valueType: 'STRING',
          },
          {
            configType: 'CONFIG',
            key: 'emptyConfig',
            rows: [],
            valueType: 'STRING',
          },
          {
            configType: 'FEATURE_FLAG',
            key: 'flag1',
            rows: [{values: [{value: {bool: true}}]}],
            valueType: 'BOOL',
          },
          {
            configType: 'FEATURE_FLAG',
            key: 'emptyFlag',
            rows: [],
            valueType: 'BOOL',
          },
          {
            configType: 'SCHEMA',
            key: 'schema1',
            rows: [{values: [{value: {bool: true}}]}],
            valueType: 'BOOL',
          },
        ],
      }

      const generator = new NodeTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      expect(result).to.equal(
        stripIndent`
      /* eslint-disable */
      // AUTOGENERATED by quonfig-cli's 'generate' command
      // prettier-ignore
      import { Quonfig, Contexts, TypedNodeServerConfigurationRaw, TypedNodeServerConfigurationAccessor } from '@quonfig/node'
      // prettier-ignore
      // No additional dependencies required

      // prettier-ignore
      type ContextObj = Record<string, Record<string, unknown>>

      // prettier-ignore
      export class QuonfigTypesafeNode {
        constructor(public quonfig: Quonfig) { }

        get<K extends keyof TypedNodeServerConfigurationRaw>(key: K, contexts?: Contexts | ContextObj): TypedNodeServerConfigurationRaw[K] {
          return this.quonfig.get(key, contexts) as TypedNodeServerConfigurationRaw[K]
        }

        config1(contexts?: Contexts | ContextObj): TypedNodeServerConfigurationAccessor['config1'] {
          return this.get('config1', contexts)
        }

        flag1(contexts?: Contexts | ContextObj): TypedNodeServerConfigurationAccessor['flag1'] {
          return this.get('flag1', contexts)
        }
      }
      ` + '\n',
      )
    })

    it('should generate function accessor methods for function configs', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'config1',
            rows: [{values: [{value: {string: 'Hello, {{name}}!'}}]}],
            valueType: 'STRING',
          },
        ],
      }

      const generator = new NodeTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      expect(result).to.equal(
        stripIndent`
      /* eslint-disable */
      // AUTOGENERATED by quonfig-cli's 'generate' command
      // prettier-ignore
      import { Quonfig, Contexts, TypedNodeServerConfigurationRaw, TypedNodeServerConfigurationAccessor } from '@quonfig/node'
      // prettier-ignore
      import Mustache from 'mustache'

      // prettier-ignore
      type ContextObj = Record<string, Record<string, unknown>>

      // prettier-ignore
      export class QuonfigTypesafeNode {
        constructor(public quonfig: Quonfig) { }

        get<K extends keyof TypedNodeServerConfigurationRaw>(key: K, contexts?: Contexts | ContextObj): TypedNodeServerConfigurationRaw[K] {
          return this.quonfig.get(key, contexts) as TypedNodeServerConfigurationRaw[K]
        }

        config1(contexts?: Contexts | ContextObj): TypedNodeServerConfigurationAccessor['config1'] {
          const raw = this.get('config1', contexts)
          return (params) => Mustache.render(raw ?? "", params)
        }
      }
      ` + '\n',
      )
    })

    it('should generate durations correctly', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'config1',
            rows: [{values: [{value: {int: 1}}]}],
            valueType: 'DURATION',
          },
        ],
      }

      const generator = new NodeTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      expect(result).to.equal(
        stripIndent`
      /* eslint-disable */
      // AUTOGENERATED by quonfig-cli's 'generate' command
      // prettier-ignore
      import { Quonfig, Contexts, TypedNodeServerConfigurationRaw, TypedNodeServerConfigurationAccessor } from '@quonfig/node'
      // prettier-ignore
      // No additional dependencies required

      // prettier-ignore
      type ContextObj = Record<string, Record<string, unknown>>

      // prettier-ignore
      export class QuonfigTypesafeNode {
        constructor(public quonfig: Quonfig) { }

        get<K extends keyof TypedNodeServerConfigurationRaw>(key: K, contexts?: Contexts | ContextObj): TypedNodeServerConfigurationRaw[K] {
          return this.quonfig.get(key, contexts) as TypedNodeServerConfigurationRaw[K]
        }

        config1(contexts?: Contexts | ContextObj): TypedNodeServerConfigurationAccessor['config1'] {
          return this.get('config1', contexts)
        }
      }
      ` + '\n',
      )
    })

    it('should prefix method names with underscore when they start with a digit', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: '1config',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            valueType: 'STRING',
          },
          {
            configType: 'FEATURE_FLAG',
            key: '1flag',
            rows: [{values: [{value: {bool: true}}]}],
            valueType: 'BOOL',
          },
        ],
      }

      const generator = new NodeTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      expect(result).to.equal(
        stripIndent`
      /* eslint-disable */
      // AUTOGENERATED by quonfig-cli's 'generate' command
      // prettier-ignore
      import { Quonfig, Contexts, TypedNodeServerConfigurationRaw, TypedNodeServerConfigurationAccessor } from '@quonfig/node'
      // prettier-ignore
      // No additional dependencies required

      // prettier-ignore
      type ContextObj = Record<string, Record<string, unknown>>

      // prettier-ignore
      export class QuonfigTypesafeNode {
        constructor(public quonfig: Quonfig) { }

        get<K extends keyof TypedNodeServerConfigurationRaw>(key: K, contexts?: Contexts | ContextObj): TypedNodeServerConfigurationRaw[K] {
          return this.quonfig.get(key, contexts) as TypedNodeServerConfigurationRaw[K]
        }

        _1Config(contexts?: Contexts | ContextObj): TypedNodeServerConfigurationAccessor['1config'] {
          return this.get('1config', contexts)
        }

        _1Flag(contexts?: Contexts | ContextObj): TypedNodeServerConfigurationAccessor['1flag'] {
          return this.get('1flag', contexts)
        }
      }
      ` + '\n',
      )
    })

    it('should properly camelCase various key formats', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'snake_case_key',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            valueType: 'STRING',
          },
          {
            configType: 'FEATURE_FLAG',
            key: 'kebab-case-key',
            rows: [{values: [{value: {bool: true}}]}],
            valueType: 'BOOL',
          },
          {
            configType: 'CONFIG',
            key: 'dot.notation.key',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            valueType: 'STRING',
          },
          {
            configType: 'FEATURE_FLAG',
            key: 'UPPER_CASE_KEY',
            rows: [{values: [{value: {bool: true}}]}],
            valueType: 'BOOL',
          },
          {
            configType: 'CONFIG',
            key: 'key_with_$_special',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            valueType: 'STRING',
          },
          {
            configType: 'FEATURE_FLAG',
            key: 'key/with/slashes',
            rows: [{values: [{value: {bool: true}}]}],
            valueType: 'BOOL',
          },
        ],
      }

      const generator = new NodeTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      expect(result).to.equal(
        stripIndent`
      /* eslint-disable */
      // AUTOGENERATED by quonfig-cli's 'generate' command
      // prettier-ignore
      import { Quonfig, Contexts, TypedNodeServerConfigurationRaw, TypedNodeServerConfigurationAccessor } from '@quonfig/node'
      // prettier-ignore
      // No additional dependencies required

      // prettier-ignore
      type ContextObj = Record<string, Record<string, unknown>>

      // prettier-ignore
      export class QuonfigTypesafeNode {
        constructor(public quonfig: Quonfig) { }

        get<K extends keyof TypedNodeServerConfigurationRaw>(key: K, contexts?: Contexts | ContextObj): TypedNodeServerConfigurationRaw[K] {
          return this.quonfig.get(key, contexts) as TypedNodeServerConfigurationRaw[K]
        }

        dotNotationKey(contexts?: Contexts | ContextObj): TypedNodeServerConfigurationAccessor['dot.notation.key'] {
          return this.get('dot.notation.key', contexts)
        }

        kebabCaseKey(contexts?: Contexts | ContextObj): TypedNodeServerConfigurationAccessor['kebab-case-key'] {
          return this.get('kebab-case-key', contexts)
        }

        keyWithSpecial(contexts?: Contexts | ContextObj): TypedNodeServerConfigurationAccessor['key_with_$_special'] {
          return this.get('key_with_$_special', contexts)
        }

        keyWithSlashes(contexts?: Contexts | ContextObj): TypedNodeServerConfigurationAccessor['key/with/slashes'] {
          return this.get('key/with/slashes', contexts)
        }

        snakeCaseKey(contexts?: Contexts | ContextObj): TypedNodeServerConfigurationAccessor['snake_case_key'] {
          return this.get('snake_case_key', contexts)
        }

        upperCaseKey(contexts?: Contexts | ContextObj): TypedNodeServerConfigurationAccessor['UPPER_CASE_KEY'] {
          return this.get('UPPER_CASE_KEY', contexts)
        }
      }` + '\n',
      )
    })

    it('should throw an error when method names conflict', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'keyWithSlashes',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            valueType: 'STRING',
          },
          {
            configType: 'CONFIG',
            key: 'key/with/slashes',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            valueType: 'STRING',
          },
        ],
      }

      const generator = new NodeTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      expect(() => generator.generate()).to.throw(
        "Method 'keyWithSlashes' is already registered. Quonfig key keyWithSlashes conflicts with 'key/with/slashes'!",
      )
    })
  })
})
