name: automerge
on:
  workflow_dispatch:
  schedule:
    - cron: '17 2,5,8,11 * * *'

jobs:
  automerge:
    permissions:
      contents: write
      pull-requests: write
      statuses: read
      checks: read
    uses: oclif/github-workflows/.github/workflows/automerge.yml@main
    secrets: inherit
