import {expect} from 'chai'
import {existsSync, readdirSync, readFileSync} from 'node:fs'
import {dirname, join} from 'node:path'
import {fileURLToPath} from 'node:url'

import {ConversionReport} from '../../src/migrate/quonfig-target/report.js'
import {
  flagOutputPath,
  segmentOutputPath,
  translateFlag,
  translateSegment,
} from '../../src/migrate/sources/launchdarkly/translate.js'
import type {LDFlag, LDSegment} from '../../src/migrate/sources/launchdarkly/types.js'

/**
 * The LaunchDarkly converter golden tests (plan §6.1 step 3).
 *
 * For every raw `fx-*.json` fixture in the canonical corpus there is a
 * hand-reviewed `expected/<fixture>.json` — the exact QuonfigFile the converter
 * must produce. This suite is table-driven: one `it()` per fixture, asserting
 * `convert(raw)` deep-equals `expected`.
 *
 * The `expected/` files are the *contract*: they were generated by
 * `scripts/generate-ld-expected.ts` and then reviewed. A converter change that
 * alters any mapping — a new operator, a different rule shape, a metadata
 * field gained or lost — fails the matching case here with a structural diff.
 * When a change to the converter's output is intentional, re-run the generator
 * script and commit the expected-file diff alongside the converter change.
 *
 * This is the structural half of §6; `launchdarkly-roundtrip.test.ts` covers
 * the semantic half (evaluate the converted output with sdk-node).
 */

const FIXTURE_DIR = join(dirname(fileURLToPath(import.meta.url)), 'fixtures', 'launchdarkly')
const RAW_DIR = join(FIXTURE_DIR, 'raw')
const EXPECTED_DIR = join(FIXTURE_DIR, 'expected')

/** A flag carries a `variations` array; a segment never does. */
function isFlag(raw: unknown): raw is LDFlag {
  return typeof raw === 'object' && raw !== null && Array.isArray((raw as {variations?: unknown}).variations)
}

function listFixtureFiles(): string[] {
  if (!existsSync(RAW_DIR)) return []
  return readdirSync(RAW_DIR)
    .filter((f) => f.endsWith('.json') && !f.startsWith('_'))
    .sort()
}

describe('migrate/sources/launchdarkly — converter golden tests', () => {
  const files = listFixtureFiles()

  it('has an expected/ output for every raw fixture (no orphans either way)', () => {
    expect(files.length, 'raw corpus is empty — did the corpus get wiped?').to.be.greaterThan(0)
    const expectedFiles = existsSync(EXPECTED_DIR)
      ? readdirSync(EXPECTED_DIR)
          .filter((f) => f.endsWith('.json'))
          .sort()
      : []
    expect(
      expectedFiles,
      `${EXPECTED_DIR} must mirror raw/ exactly — run scripts/generate-ld-expected.ts`,
    ).to.deep.equal(files)
  })

  for (const file of files) {
    it(`converts ${file} to its golden expected/ output`, () => {
      const raw = JSON.parse(readFileSync(join(RAW_DIR, file), 'utf8')) as unknown
      const report = new ConversionReport()

      const actual = isFlag(raw) ? translateFlag(raw, report) : translateSegment(raw as LDSegment, report)

      const expectedPath = join(EXPECTED_DIR, file)
      expect(
        existsSync(expectedPath),
        `missing golden file ${expectedPath} — run scripts/generate-ld-expected.ts`,
      ).to.equal(true)
      const expected = JSON.parse(readFileSync(expectedPath, 'utf8')) as unknown

      expect(actual, `converter output for ${file} drifted from its golden expected/ output`).to.deep.equal(expected)
    })

    it(`emits the canonical output path for ${file}`, () => {
      const raw = JSON.parse(readFileSync(join(RAW_DIR, file), 'utf8')) as unknown
      const path = isFlag(raw) ? flagOutputPath(raw.key) : segmentOutputPath((raw as LDSegment).key)
      // Flags land under feature-flags/, segments under segments/ — flat, one file per key.
      const expectedPrefix = isFlag(raw) ? 'feature-flags/' : 'segments/'
      expect(path).to.match(new RegExp(`^${expectedPrefix}[^/]+\\.json$`))
    })
  }
})
